version: '3.8'

services:
  wg-easy:
    image: weejewel/wg-easy

# New Repository: https://github.com/wg-easy/wg-easy            (application is not password enabled)
# ghcr.io/wg-easy/wg-easy

# Old Repository: https://hub.docker.com/r/weejewel/wg-easy     (application is password enabled)    
# weejewel/wg-easy

    container_name: wg-easy
    environment:
      - PASSWORD=Password@786               # Replace with a strong password for the admin interface
      - WG_HOST=54.90.88.71                 # Replace with your domain or public IP
#      - WG_PORT=51820                       # WireGuard port (optional, default is 51820)
#      - WG_DEFAULT_ADDRESS=10.8.0.x         # Default IP range for clients (optional)
#      - WG_DEFAULT_DNS=1.1.1.1              # Default DNS for clients (optional)
    volumes:
      - ./config:/etc/wireguard              # Persistent storage for WireGuard config
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    privileged: true                        # Required to access the host's network stack
